# Generated by Django 6.0.3 on 2026-04-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_is_writer_customuser_consent_given_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_writer',
            field=models.BooleanField(default=False),
        ),
    ]
