# Generated by Django 6.0.3 on 2026-04-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_consent_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_writer_requested',
            field=models.BooleanField(default=False),
        ),
    ]
