# Generated by Django 6.0.3 on 2026-04-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_is_writer_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='writer_reason',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
    ]
