# Generated by Django 6.0.3 on 2026-05-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_customuser_writer_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
