# Generated by Django 6.0.3 on 2026-05-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='writer_reason',
            field=models.TextField(blank=True),
        ),
    ]
