# Generated by Django 6.0.3 on 2026-04-26 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('writer', '0005_category_tag_alter_article_user_article_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('user', 'article')},
        ),
    ]
