# Generated by Django 6.0.3 on 2026-04-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0003_article_image_articleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
