# Generated by Django 6.0.3 on 2026-05-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0005_category_tag_alter_article_user_article_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
